### ISSUE TITLE
After update to 2.0.3 receive an error stating that .set does not exist in MockDate

### ISSUE THREAD

**Issue by Pipeman** [boblauer/MockDate#26]
I have the following two lines of code in a TS file

```
import * as MockDate from 'mockdate';

MockDate.set('12/18/2017');
```
After updating to 2.0.3 both VSCode and in building phase I receive an error stating:
```
TS2339: Property 'set' does not exist on type 'typeof import("/path/to/project/node_modules/mockdate/index")'.
```
If I either downgrade to 2.0.2 or manually remove the `index.d.ts` file the error goes away

**Comment by patrikvarga** [comment]
The 2.0.2 --> 2.0.3 change also broke the `resetDate` API which is now `reset`.

This was not a backwards-compatible change.

**Comment by Hoishin** [comment]
It is because the recently added type definition is wrong. It shouldn't use `export default` for CommonJS `module.exports = `

**Comment by phts** [comment]
After 2.0.4 still getting error from `tsc`.

```
> tsc --noEmit                                                                                                                                                                                                            
                                                                                                                                                                                                                          
node_modules/mockdate/index.d.ts:7:67 - error TS1005: '{' expected.                                                                                                                                                       
                                                                                                                                                                                                                          
7   set(date: Date | string | number, timezoneOffset?: number): void,                                                                                                                                                     
                                                                    ~                                                                                                                                                     
```

BTW why needed `index.d.ts` here if there is already type [`@types/mockdate`](https://www.npmjs.com/package/@types/mockdate) which always works well. `index.d.ts` here is redundant I suppose, moreover it is not working and prevents from using `@types`.

**Comment by Hoishin** [comment]
`@types/*` packages are meant to serve type definitions for packages without type defintions. If package maintainer can serve its definitions it's preferred because you don't have to install extra packages.
Though, if maintainers cannot maintain the type definitions it should go `@types` instead of building into package IMO.

**Comment by jakubriedl** [comment]
I think maintainers should include their definitions so they are part of codebase and evolve with it.
The issue is that the definition file is incorrect.
this is what we use for overwrite
```
declare module 'mockdate' {
  export function set(
    date: Date | string | number,
    timezoneOffset?: number
  ): void
  export function reset(): void
}
```

**Comment by Hoishin** [comment]
Yes, that is ideal. But if maintainers cannot or are not capable of updating/correcting/reviewing type definition, it shouldn't be part of this codebase and have to be part of DefinitelyTyped (`@types/*`) (which is the reason why DefinitelyTyped exists)

**Comment by pietro909** [comment]
Agree with @Hoishin it doesn't look like the maintainers want/can look after TS definitions. In this case, it is better to leave them to the community.
This issue screws up the CI, there are 3 open PRs for this and it they are pretty small to review compared to the benefit they bring.

**Comment by boblauer** [comment]
I know this issue is old, but fwiw I just rewrote the library in TypeScript.

**Comment by patrikvarga** [comment]
Well, thanks for doing so and letting us know @boblauer!

**Comment by Pipeman** [comment]
@boblauer Noice, thanks!
